(function(){
'use strict';
var cfg=window.SUPABASE_CONFIG||{}, base=(cfg.url||'').replace(/\/$/,''), session=null;
var loginView=document.getElementById('login-view'), appView=document.getElementById('app-view'), warning=document.getElementById('config-warning');
function configured(){return base&&cfg.anonKey&&base.indexOf('YOUR-PROJECT')<0&&cfg.anonKey.indexOf('YOUR_')!==0;}
if(!configured())warning.classList.remove('hidden');
function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]});}
function toast(msg,bad){var t=document.getElementById('toast');t.textContent=msg;t.style.color=bad?'#ff9292':'#6af09a';t.style.borderColor=bad?'rgba(255,87,87,.4)':'rgba(37,211,102,.4)';t.classList.remove('hidden');clearTimeout(t._x);t._x=setTimeout(function(){t.classList.add('hidden');},2800);}
function token(){return session&&session.access_token;}
function headers(extra){return Object.assign({apikey:cfg.anonKey,Authorization:'Bearer '+token(),'Content-Type':'application/json'},extra||{});}
async function api(table,query,options){var r=await fetch(base+'/rest/v1/'+table+(query?'?'+query:''),Object.assign({headers:headers()},options||{}));if(r.status===401){logout();throw new Error('Session expired. Login again.');}if(!r.ok)throw new Error(await r.text()||('HTTP '+r.status));var text=await r.text();return text?JSON.parse(text):[];}
async function list(table){return api(table,'select=*&order=sort_order.asc');}
async function save(table,id,data){data.updated_at=new Date().toISOString();if(id)return api(table,'id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:headers({Prefer:'return=representation'}),body:JSON.stringify(data)});return api(table,'',{method:'POST',headers:headers({Prefer:'return=representation'}),body:JSON.stringify(data)});}
async function remove(table,id){return api(table,'id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:headers({Prefer:'return=minimal'})});}
async function upload(file,folder){if(!file)return '';var safe=(Date.now()+'-'+file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-'));var path=folder+'/'+safe,bucket=cfg.mediaBucket||'site-media';var r=await fetch(base+'/storage/v1/object/'+bucket+'/'+path,{method:'POST',headers:{apikey:cfg.anonKey,Authorization:'Bearer '+token(),'Content-Type':file.type||'application/octet-stream','x-upsert':'true'},body:file});if(!r.ok)throw new Error(await r.text());return base+'/storage/v1/object/public/'+bucket+'/'+path;}
function showApp(){loginView.classList.add('hidden');appView.classList.remove('hidden');loadAll();}
function logout(){session=null;localStorage.removeItem('mb_admin_session');appView.classList.add('hidden');loginView.classList.remove('hidden');}
document.getElementById('logout').onclick=logout;
document.getElementById('login-form').addEventListener('submit',async function(e){e.preventDefault();var err=document.getElementById('login-error');err.textContent='';if(!configured()){err.textContent='config.js setup করা হয়নি।';return;}var btn=e.submitter;btn.disabled=true;try{var r=await fetch(base+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:cfg.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('login-email').value,password:document.getElementById('login-password').value})});var data=await r.json();if(!r.ok)throw new Error(data.error_description||data.msg||'Login failed');session=data;localStorage.setItem('mb_admin_session',JSON.stringify(data));showApp();}catch(x){err.textContent=x.message;}finally{btn.disabled=false;}});
document.querySelectorAll('.tab').forEach(function(b){b.onclick=function(){document.querySelectorAll('.tab,.pane').forEach(function(x){x.classList.remove('active');});b.classList.add('active');document.getElementById('pane-'+b.dataset.tab).classList.add('active');};});
function formData(form,fields){var out={};fields.forEach(function(k){var e=form.elements[k];out[k]=e.type==='checkbox'?e.checked:e.value.trim();});if('sort_order'in out)out.sort_order=Number(out.sort_order)||0;return out;}
function reset(form){form.reset();form.elements.id.value='';if(form.elements.active)form.elements.active.checked=true;if(form.elements.sort_order)form.elements.sort_order.value=0;if(form.elements.headline)form.elements.headline.value='FULL VIRAL CONTENT';}
document.querySelectorAll('[data-cancel],[data-new]').forEach(function(b){b.onclick=function(){var n=b.dataset.cancel||b.dataset.new;reset(document.getElementById(n+'-form'));};});
var cache={packages:[],stats:[],demos:[]};
function mini(url){return url?'<img class="thumb-mini" src="'+esc(url)+'" alt="">':'<div class="thumb-mini">◆</div>';}
function renderPackages(){var el=document.getElementById('package-items');el.innerHTML=cache.packages.length?cache.packages.map(function(x){return '<div class="item">'+mini(x.image_url)+'<div><h3>'+esc(x.title)+' — ৳'+esc(x.price)+'</h3><p>'+esc(x.description||'No description')+'</p></div><div class="item-actions"><button class="secondary" data-edit-package="'+x.id+'">Edit</button><button class="danger" data-delete-package="'+x.id+'">Delete</button></div></div>';}).join(''):'<div class="empty">এখনো কোনো package যোগ করা হয়নি।</div>';bindItems();}
function renderStats(){var el=document.getElementById('stat-items');el.innerHTML=cache.stats.length?cache.stats.map(function(x){return '<div class="item"><div class="thumb-mini">'+esc(x.value)+'</div><div><h3>'+esc(x.label)+'</h3><p>Order: '+x.sort_order+(x.active?' · Active':' · Hidden')+'</p></div><div class="item-actions"><button class="secondary" data-edit-stat="'+x.id+'">Edit</button><button class="danger" data-delete-stat="'+x.id+'">Delete</button></div></div>';}).join(''):'<div class="empty">এখনো কোনো stat যোগ করা হয়নি।</div>';bindItems();}
function renderDemos(){var el=document.getElementById('demo-items');el.innerHTML=cache.demos.length?cache.demos.map(function(x){return '<div class="item">'+mini(x.thumbnail_url)+'<div><h3>'+esc(x.title)+'</h3><p>'+esc(x.video_url||'Coming soon')+'</p></div><div class="item-actions"><button class="secondary" data-edit-demo="'+x.id+'">Edit</button><button class="danger" data-delete-demo="'+x.id+'">Delete</button></div></div>';}).join(''):'<div class="empty">এখনো কোনো demo video যোগ করা হয়নি।</div>';bindItems();}
function fill(form,row,fields){fields.forEach(function(k){if(form.elements[k]){if(form.elements[k].type==='checkbox')form.elements[k].checked=!!row[k];else form.elements[k].value=row[k]==null?'':row[k];}});form.elements.id.value=row.id;form.scrollIntoView({behavior:'smooth',block:'start'});}
function bindItems(){document.querySelectorAll('[data-edit-package]').forEach(function(b){b.onclick=function(){fill(document.getElementById('package-form'),cache.packages.find(function(x){return String(x.id)===b.dataset.editPackage;}),['title','price','image_url','headline','description','sort_order','active']);};});document.querySelectorAll('[data-edit-stat]').forEach(function(b){b.onclick=function(){fill(document.getElementById('stat-form'),cache.stats.find(function(x){return String(x.id)===b.dataset.editStat;}),['value','label','sort_order','active']);};});document.querySelectorAll('[data-edit-demo]').forEach(function(b){b.onclick=function(){fill(document.getElementById('demo-form'),cache.demos.find(function(x){return String(x.id)===b.dataset.editDemo;}),['title','video_url','thumbnail_url','description','sort_order','active']);};});document.querySelectorAll('[data-delete-package],[data-delete-stat],[data-delete-demo]').forEach(function(b){b.onclick=async function(){var type=b.hasAttribute('data-delete-package')?'package':b.hasAttribute('data-delete-stat')?'stat':'demo',table=type==='package'?'packages':type==='stat'?'stats':'demos',id=b.dataset['delete'+type.charAt(0).toUpperCase()+type.slice(1)];if(!confirm('Delete this item?'))return;try{await remove(table,id);toast('Deleted');await loadLists();}catch(e){toast(e.message,true);}};});}
async function loadSettings(){var rows=await api('site_settings','id=eq.1&select=*'),x=rows[0]||{};var f=document.getElementById('settings-form');['hero_title','hero_subtitle','whatsapp','telegram','facebook','youtube','footer_text'].forEach(function(k){f.elements[k].value=x[k]||'';});}
async function loadLists(){var all=await Promise.all([list('packages'),list('stats'),list('demos')]);cache.packages=all[0];cache.stats=all[1];cache.demos=all[2];renderPackages();renderStats();renderDemos();}
async function loadAll(){try{await Promise.all([loadSettings(),loadLists()]);}catch(e){toast(e.message,true);}}
document.getElementById('settings-form').addEventListener('submit',async function(e){e.preventDefault();var d=formData(e.currentTarget,['hero_title','hero_subtitle','whatsapp','telegram','facebook','youtube','footer_text']);try{await api('site_settings','id=eq.1',{method:'PATCH',headers:headers({Prefer:'return=minimal'}),body:JSON.stringify(Object.assign(d,{updated_at:new Date().toISOString()}))});toast('Settings saved');}catch(x){toast(x.message,true);}});
document.getElementById('package-form').addEventListener('submit',async function(e){e.preventDefault();var f=e.currentTarget,b=e.submitter;b.disabled=true;try{var d=formData(f,['title','price','image_url','headline','description','sort_order','active']),file=f.elements.image_file.files[0];if(file)d.image_url=await upload(file,'packages');await save('packages',f.elements.id.value,d);reset(f);toast('Package saved');await loadLists();}catch(x){toast(x.message,true);}finally{b.disabled=false;}});
document.getElementById('stat-form').addEventListener('submit',async function(e){e.preventDefault();var f=e.currentTarget;try{await save('stats',f.elements.id.value,formData(f,['value','label','sort_order','active']));reset(f);toast('Stat saved');await loadLists();}catch(x){toast(x.message,true);}});
document.getElementById('demo-form').addEventListener('submit',async function(e){e.preventDefault();var f=e.currentTarget,b=e.submitter;b.disabled=true;try{var d=formData(f,['title','video_url','thumbnail_url','description','sort_order','active']),file=f.elements.thumbnail_file.files[0];if(file)d.thumbnail_url=await upload(file,'demos');await save('demos',f.elements.id.value,d);reset(f);toast('Demo saved');await loadLists();}catch(x){toast(x.message,true);}finally{b.disabled=false;}});
try{session=JSON.parse(localStorage.getItem('mb_admin_session')||'null');}catch(e){}if(session&&configured())showApp();
})();
